baseurl = "https://kryptokrauts.com/"
title = "kryptokrauts"
# Enable comments by entering your Disqus shortname
disqusShortname = "kryptokrauts"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "â†©"
theme = "hugo-icarus-theme"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

[Languages]
[Languages.de]
LanguageName = "Deutsch"

[Languages.en]
LanguageName = "English"

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
# Menu different for each language
[[Languages.de.menu.main]]
    weight = 1
    name  = "Mach mit!"
    url   = "/join-us/"
[[Languages.de.menu.main]]
    weight = 2
    name  = "Kryptospace Grundlagen"
    url   = "/basic-knowledge/"
[[Languages.de.menu.main]]
    weight = 3
    name  = "Expertenwissen"
    url   = "/expert-knowledge/"
[[Languages.de.menu.main]]
    weight = 4
    name  = "Trading"
    url   = "/trading/"
[[Languages.de.menu.main]]
    weight = 5
    name  = "Tracking & Steuer"
    url   = "/tracking-taxation/"
[[Languages.de.menu.main]]
    weight = 6
    name  = "Glossar"
    url   = "/glossar/"

[[Languages.en.menu.main]]
    weight = 1
    name  = "Join us!"
    url   = "/join-us/"
[[Languages.en.menu.main]]
    weight = 2
    name  = "Cryptospace basics"
    url   = "/basic-knowledge/"
[[Languages.en.menu.main]]
    weight = 3
    name  = "Expert knowledge"
    url   = "/expert-knowledge/"
[[Languages.en.menu.main]]
    weight = 4
    name  = "Trading"
    url   = "/trading/"
[[Languages.en.menu.main]]
    weight = 5
    name  = "Tracking & Taxation"
    url   = "/tracking-taxation/"
[[Languages.en.menu.main]]
    weight = 6
    name  = "Glossar"
    url   = "/glossar/"

[permalinks]
    announcement = "/:sections/:year/:month/:day/:slug"
    basic-knowledge = "/:sections/:year/:month/:day/:slug"
    expert-knowledge = "/:sections/:year/:month/:day/:slug"
    trading = "/:sections/:year/:month/:day/:slug"
    tracking-taxation = "/:sections/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "kryptokrauts"
    bio = "blockchain - crypto - decentralization - tokenization"
    location = "global"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "you@example.com"
    logo = "css/images/logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["announcement", "basic-knowledge", "expert-knowledge", "trading", "tracking-taxation"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/kryptokrauts"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "kryptokrauts"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "kryptokrauts"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.speakerDeck]
    disable = false
  [privacy.twitter]
    disable = false
    enableDNT = false
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = false